version: "3.2"
services:
  
  jwt:
    volumes:
        - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh
  reportes:
    volumes:
        - ./reportes/:/mnt/
    build: ./reportes
    working_dir: /backend/
    command: sh run.sh
  historia_clinica:
    volumes:
        - ./historia_clinica/:/mnt/
    build: ./historia_clinica
    working_dir: /backend/
    command: sh run.sh
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - jwt
